diffpy/diffpy.morph

diffpy/pdfmorph/tests/test_morphrgrid.py, diffpy/pdfmorph/tests/test_tools.py
Rename `assertAlmostEquals` --> `assertAlmostEqual`.
=> MNT: replace deprecated test methods

.gitignore, diffpy/pdfmorph/pdfmorphapp.py, doc/source/index.rst
=> added DS_store to ignore and test edit

.github/workflows/main.yml, environment.yml, requirements/run.txt
=> Add GH actions for CI

diffpy/pdfmorph/pdfmorphapp.py
closes #44 
Here's before
and after
and here is the new save file that it creates for the morphed PDF in case we should avoid altering the file format I can revert the additional parameters in the save file.
=> Added input morph parameters to the output

README.rst
closes #85 
Addressed:
Add --yes to conda create -n pdfmorph_env python=3 command
Remove duplicated conda config --add channels conda-forge
Change easy_install --update to pip <command>
Replace travis badge with gh status badge
I believe bg-mpl-stylesheets is downloading properly as well.
=> Addressing Issue 85

README.rst
Remove mention of `.sh` for pre-commit and bump required python versions.
=> Update REAME.rst instructions

.pre-commit-config.yaml
The PyCharm default character limit per line is 120, and I think the longer lines (~115) makes the code less cluttered.
When using `Black`, it is [recommended](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#labels-why-pycodestyle-warnings) to ignore `E203`, `E701`, `E704`, `W503`. By default, `W503` should be disabled by `flake8`, but removing that warning from `ignore` gives a bunch of those errors.
=> Bump flake8 version

README.rst
https://github.com/diffpy/diffpy.pdfmorph/actions/workflows/matrix-and-codecov-on-merge-to-main.yml/badge.svg
Works now..
=> Fix typo in CI badge

news/explicit_paths.rst, src/diffpy/pdfmorph/tools.py
See https://github.com/diffpy/diffpy.utils/pull/164
=> Fix tools diffpy.utils paths

news/new_parser_api.rst, src/diffpy/pdfmorph/tools.py
=> fix: import `loadData` and `deserialize_data` directly to adopt new API from `diffpy.utils(3.6.0)`

news/morphsqueeze.rst, src/diffpy/morph/morphs/morphsqueeze.py, tests/test_morphsqueeze.py
I have written different UCs tests from issue 181 for the squeeze morph. I am keeping the morphed x-axis the same as the unmorphed as we discussed. I have left the morph function empty. My inputs are a uniform target, and a squeezed morph, then the expected morph is the unsqueezed morph.
=> Squeeze morph: Adding UCs tests

news/morphfuncy.rst, src/diffpy/morph/morphs/morphfuncy.py, tests/test_morphfuncy.py
I have created a draft for the `MorphFuncy` class and tested it using different functions with various parameters that I have defined using `pytest.parametrize`. I am currently defining the parameters for the functions as a dictionary, where each function has its specific parameters. I'm unsure if using a dictionary is the best decision. We can implement more options such as if the user does not provide a function to raise a warning or something similar.
=> test/func: created a test and function for MorphFuncy

news/dict_lists_refinement.rst, src/diffpy/morph/morph_api.py, src/diffpy/morph/morphs/__init__.py, src/diffpy/morph/morphs/morphfuncy.py, src/diffpy/morph/morphs/morphsqueeze.py, src/diffpy/morph/refine.py, tests/test_morph_func.py, tests/test_morphfuncy.py, tests/test_morphsqueeze.py
I have modified the `refine.py` to allow refinement of scalars, lists, and dictionaries (before it was only scalars). I have done this by flattening lists and dictionaries accordingly and then reconstructing and regrouping the lists or dictionaries after refinement.
I have also added `MorphSqueeze` and `MorphFuncy` into `morph_api.py` and `_init_.py`. I have finally tested that we can now refine `MorphSqueeze` and `MorphFuncy` and I added these tests in `test_morph_func.py` where there are tests for other morphs as well. The tests are successful and therefore now we can refine squeeze and funcy. I am attaching some figures from the tests here. Finally, I also run all the tests for all the diffpy.morph, such as `test_refine.py`, etc., to make sure everything is working properly and they …
=> Enable refinement of lists and dictionary input parameters

news/add-docformatter.rst, pyproject.toml, src/diffpy/morph/morph_helpers/__init__.py, src/diffpy/morph/morph_io.py, src/diffpy/morph/morphs/morphfuncy.py, src/diffpy/morph/morphs/morphresolution.py, src/diffpy/morph/plot.py, src/diffpy/morph/tools.py
Closes #213 
This PR adds a ``docformatter`` config block to ``pyproject.toml`` and pre-commit is ran to apply the new configs to all the files in the project. Please check the modifications.
=> ci: add docformatter config to pyproject.toml and apply them to the files

news/tolerance.rst, src/diffpy/morph/morphapp.py, src/diffpy/morph/refine.py, tests/test_refine.py
=> Add tolerance option

news/smear_pdf_bug.rst, src/diffpy/morph/morph_helpers/transformrdftopdf.py
See change in-line. When converting from RDF to PDF, a division by `r` is done. Since we know the point at which `r=0` corresponds to `g(r=0)=0`, we set `g(r=0)=0` to avoid a divide-by-zero. The setting for the morph `g(r)` incorrectly uses the target `r`-grid to do this setting to zero.
=> Bug fix for `--smear-pdf`

news/epsilon.rst, src/diffpy/morph/morphs/morphrgrid.py
The intent of `epsilon` is to ensure that the `rmax` point is excluded. By setting `epsilon = rstep/2`, we ensure that only that last point is excluded, even on denser grids (i.e. grids denser than `rstep=1e-08`).
=> Move epsilon parameter in `MorphRGrid`

news/kwargs.rst, src/diffpy/morph/morphpy.py
This is a docstring update. Prior to this, we get a warning if any of our kwarg entries are not dicts. The kwargs entry is supposed to denote the possible entry types, not that kwargs is a dict.
=> Change kwargs input from dict to any

news/no-subprocess.rst, tests/test_morphsqueeze.py, tests/test_refine.py
New tests from #249 and #250 give errors on Windows. Running as shell command (in the case of Windows) is not recommended.
We don't need to call the subprocess since we can directly simulate a CLI call similar to the tests already present in `test_morphapp.py`.
=> Remove subprocess calls from tests

news/reduce-warns.rst, src/diffpy/morph/morph_io.py, src/diffpy/morph/morphapp.py, src/diffpy/morph/morphs/morphsqueeze.py, tests/test_morphsqueeze.py
Update to #250, which would throw a warning each step of the refinement. We only want the user to see the warning afterward since only that quantity is useful.
Targets first check point of #243
=> Only warn user about `squeeze` extrapolation after refinement

news/extrap-warnings.rst, src/diffpy/morph/morph_io.py, src/diffpy/morph/morphapp.py, src/diffpy/morph/morphs/morph.py, src/diffpy/morph/morphs/morphshift.py, src/diffpy/morph/morphs/morphsqueeze.py, tests/test_morphsqueeze.py
address issues mentioned in #243. 
Refactor the code to throw extrapolation warnings and throw an extrapolation warning for `morph_shift`.
In this PR,
1. `checkExtrapolation` is implemented at `morph.Morph` to make it accessible to all derived classes.
2.  Interfaces of related functions are changed to adopt `checkExtrapolation`'s output.
=> feat: add `set_extrapolation_info` function in `morph.Morph`
